# Generated by Django 3.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20240705_1812'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(
                fields=['latest_action_date'],
                name='opencivicdata_bill_latest_action_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(
                fields=['updated_at'],
                name='opencivicdata_bill_updated_at_idx',
            ),
        ),
    ]
