# Generated by Django 3.2.14 on 2026-08-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_bill_indexes'),
        ('data', '0047_billversiondocument_diff_from_previous_version'),
    ]

    operations = [
    ]
